<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecimenTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('specimen_types')->delete();

        DB::table('specimen_types')->insert(array(
            0 =>
            array(
                'id' => 1,
                'code_label' => 'A',
                'code' => '1',
                'label' => 'Blood (Dried spot)',
                'description' => 'Dried bloodspot from finger prick or heel prick',
                'transport_method' => 1,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 =>
            array(
                'id' => 2,
                'code_label' => 'B',
                'code' => '2',
                'label' => 'Lithium heparin',
                'description' => 'Blood (Li-Hep)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'code_label' => 'C',
                'code' => '3',
                'label' => 'Stool(Fresh)',
                'description' => 'Direct poo',
                'transport_method' => 2,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'code_label' => 'D',
                'code' => '4',
                'label' => 'Blood(FI_Ox)',
                'description' => 'Venous blood in Fluoride Oxalate tube',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 1,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 =>
            array(
                'id' => 5,
                'code_label' => 'E',
                'code' => '5',
                'label' => 'Blood(EDTA)',
                'description' => 'Venous blood or capillary blood iin EDTA tube',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 1,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'code_label' => 'F',
                'code' => '6',
                'label' => 'Filter paper',
                'description' => 'Blood (dried spot)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'code_label' => 'G',
                'code' => '7',
                'label' => 'Quantiferon',
                'description' => 'Blood (QF)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 =>
            array(
                'id' => 8,
                'code_label' => 'H',
                'code' => '8',
                'label' => 'Blood (Hep)',
                'description' => 'Venous blood in heparin tubes',
                'transport_method' => 1,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 =>
            array(
                'id' => 9,
                'code_label' => 'i',
                'code' => '9',
                'label' => 'EDTA immunology',
                'description' => 'Blood (EDTA, Amb)',
                'transport_method' => 0,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 =>
            array(
                'id' => 10,
                'code_label' => 'J',
                'code' => '10',
                'label' => 'Skin smear',
                'description' => 'Skin smear',
                'transport_method' => 0,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 =>
            array(
                'id' => 11,
                'code_label' => 'K',
                'code' => '11',
                'label' => 'Formalin urine',
                'description' => 'Urine (Formalin)',
                'transport_method' => 0,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 =>
            array(
                'id' => 12,
                'code_label' => 'L',
                'code' => '12',
                'label' => 'Blood culture',
                'description' => 'Blood (Culture)',
                'transport_method' => 0,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 =>
            array(
                'id' => 13,
                'code_label' => 'M',
                'code' => '13',
                'label' => 'Cheek cell swabs',
                'description' => 'Swab (Cheek cell)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 =>
            array(
                'id' => 14,
                'code_label' => 'N',
                'code' => '14',
                'label' => 'Blood (Serum)',
                'description' => 'Venous or capillary (fingerprick or heel prick) collected in plain tube or in clot activator tube',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 1,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 =>
            array(
                'id' => 15,
                'code_label' => 'O',
                'code' => '15',
                'label' => 'Malaria thick film',
                'description' => 'Blood (Thick film)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 =>
            array(
                'id' => 16,
                'code_label' => 'P',
                'code' => '16',
                'label' => 'Paxgene',
                'description' => 'Blood (Paxgene)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 =>
            array(
                'id' => 17,
                'code_label' => 'Q',
                'code' => '17',
                'label' => 'Sodium citrate blood',
                'description' => 'Blood (Na-Cit)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 =>
            array(
                'id' => 18,
                'code_label' => 'R',
                'code' => '18',
                'label' => 'Fluid including CSF',
                'description' => 'Fluid (e.g. CSF)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 =>
            array(
                'id' => 19,
                'code_label' => 'S',
                'code' => '19',
                'label' => 'Formalin stool',
                'description' => 'Stool (Formalin)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 =>
            array(
                'id' => 20,
                'code_label' => 'T',
                'code' => '20',
                'label' => 'Swab (Throat)',
                'description' => 'Swabbing of the throat',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 =>
            array(
                'id' => 21,
                'code_label' => 'U',
                'code' => '21',
                'label' => 'Urine (Fresh)',
                'description' => 'Early catch urine or Midstream urine (MSU), can also be 24 hour urine or random (spot) urine',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 =>
            array(
                'id' => 22,
                'code_label' => 'V',
                'code' => '22',
                'label' => 'Saliva',
                'description' => 'Spitting or using swab',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 =>
            array(
                'id' => 23,
                'code_label' => 'W',
                'code' => '23',
                'label' => 'Swab (Pernasal)',
                'description' => 'Swabbing the posterior nasopharynx',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 =>
            array(
                'id' => 24,
                'code_label' => 'Y',
                'code' => '24',
                'label' => 'Unknown',
                'description' => 'Unknown',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 =>
            array(
                'id' => 25,
                'code_label' => 'Z',
                'code' => '25',
                'label' => 'Other microbiology',
                'description' => 'Other (micro)',
                'transport_method' => 0,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 =>
            array(
                'id' => 26,
                'code_label' => '1',
                'code' => '26',
                'label' => 'Swab(Nose&throat)',
                'description' => 'Swabbing the throat and Nose',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 =>
            array(
                'id' => 27,
                'code_label' => '2',
                'code' => '27',
                'label' => 'Swab(Nasal)',
                'description' => 'Swabbing the nose',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 =>
            array(
                'id' => 28,
                'code_label' => '28',
                'code' => '28',
                'label' => 'Swab (vaginal)',
                'description' => 'Swabbing the vaginal',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 =>
            array(
                'id' => 29,
                'code_label' => '29',
                'code' => '29',
                'label' => 'Swab (faecal)',
                'description' => 'Swabbing the diapers or stool',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 =>
            array(
                'id' => 30,
                'code_label' => '30',
                'code' => '30',
                'label' => 'Swab (skin)',
                'description' => 'Swabbing the skin',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 =>
            array(
                'id' => 31,
                'code_label' => '31',
                'code' => '31',
                'label' => 'Hair',
                'description' => 'Cutting of human hair',
                'transport_method' => 1,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 =>
            array(
                'id' => 32,
                'code_label' => '32',
                'code' => '32',
                'label' => 'Breast milk',
                'description' => 'Breast milk collected through hand expression or using a pump',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 =>
            array(
                'id' => 33,
                'code_label' => '33',
                'code' => '33',
                'label' => 'Blood (tempus)',
                'description' => 'Venous in tempus tube',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 1,
                'total_aliquots' => 3,
                'taken_from_blood' => 1,
                'is_active' => 0,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 =>
            array(
                'id' => 34,
                'code_label' => '34',
                'code' => '34',
                'label' => 'Placenta(formalin) (A)',
                'description' => 'Placenta tissue collected using biopsy punch or any vessel and stored in formalin (from location A)',
                'transport_method' => 2,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 1,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 =>
            array(
                'id' => 35,
                'code_label' => '35',
                'code' => '35',
                'label' => 'Placenta(RNA protect) (A)',
                'description' => 'Placenta tissue collected using biopsy punch or any vessel and stored in RNA protect (from location A)',
                'transport_method' => 2,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 1,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 =>
            array(
                'id' => 36,
                'code_label' => '36',
                'code' => '36',
                'label' => 'Placenta (formalin) B',
                'description' => 'Placenta tissue collected using biopsy punch or any vessel and stored in formalin (from location B)',
                'transport_method' => 2,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 1,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 =>
            array(
                'id' => 37,
                'code_label' => '37',
                'code' => '37',
                'label' => 'Placenta (RNA Protect) B',
                'description' => 'Placenta tissue collected using biopsy punch or any vessel and stored in RNA protect (from location B)',
                'transport_method' => 2,
                'has_aliquot' => 0,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 0,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 =>
            array(
                'id' => 38,
                'code_label' => '38',
                'code' => '38',
                'label' => 'Swab (Placenta Maternal)',
                'description' => 'Swabbing from maternal side of the placenta',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 =>
            array(
                'id' => 39,
                'code_label' => '39',
                'code' => '39',
                'label' => 'Swab (Placenta foetal)',
                'description' => 'Swabbing from foetal side of the placenta',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 =>
            array(
                'id' => 40,
                'code_label' => '40',
                'code' => '40',
                'label' => 'Swab (Rectal)',
                'description' => 'Swabbing of the rectum',
                'transport_method' => 2,
                'has_aliquot' => 1,
                'is_placenta_tissue' => 0,
                'total_aliquots' => 3,
                'taken_from_blood' => 0,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
    }
}
