<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SpecimensTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('specimens')->delete();
        
        \DB::table('specimens')->insert(array (
            0 => 
            array (
                'labno' => '1111111',
                'specno' => '0000000',
                'spectype' => 14,
                'stid' => '2231397',
                'cno' => NULL,
                'accForm' => 'TestEntry',
                'repeat_sample' => 0,
                'pregnant' => NULL,
                'curmens' => 0,
                'mens2d' => 0,
                'basefoll' => NULL,
                'fast' => NULL,
                'venepunc' => NULL,
                'volume' => NULL,
                'tubes' => NULL,
                'stooltype' => NULL,
                'stoolusual' => NULL,
                'spectime' => NULL,
                'datecol' => '2025-01-01',
                'timeprod' => NULL,
                'timeint' => NULL,
                'iohexol' => NULL,
                'dateinlab' => NULL,
                'timeinlab' => NULL,
                'staffcode' => NULL,
                'labstaff' => NULL,
                'checker' => NULL,
                'rcdr' => NULL,
                'version' => 1,
                'created_at' => '2025-09-02 15:09:50',
                'updated_at' => '2025-09-02 15:09:50',
            ),
            1 => 
            array (
                'labno' => '1111112',
                'specno' => '0000001',
                'spectype' => 4,
                'stid' => '2231397',
                'cno' => NULL,
                'accForm' => 'TestEntry',
                'repeat_sample' => 0,
                'pregnant' => NULL,
                'curmens' => 0,
                'mens2d' => 0,
                'basefoll' => NULL,
                'fast' => NULL,
                'venepunc' => NULL,
                'volume' => NULL,
                'tubes' => NULL,
                'stooltype' => NULL,
                'stoolusual' => NULL,
                'spectime' => NULL,
                'datecol' => '2025-01-01',
                'timeprod' => NULL,
                'timeint' => NULL,
                'iohexol' => NULL,
                'dateinlab' => NULL,
                'timeinlab' => NULL,
                'staffcode' => NULL,
                'labstaff' => NULL,
                'checker' => NULL,
                'rcdr' => NULL,
                'version' => 1,
                'created_at' => '2025-09-02 15:10:46',
                'updated_at' => '2025-09-02 15:10:46',
            ),
            2 => 
            array (
                'labno' => '1111113',
                'specno' => '0000002',
                'spectype' => 5,
                'stid' => '2231397',
                'cno' => NULL,
                'accForm' => 'TestEntry',
                'repeat_sample' => 0,
                'pregnant' => NULL,
                'curmens' => 0,
                'mens2d' => 0,
                'basefoll' => NULL,
                'fast' => NULL,
                'venepunc' => NULL,
                'volume' => NULL,
                'tubes' => NULL,
                'stooltype' => NULL,
                'stoolusual' => NULL,
                'spectime' => NULL,
                'datecol' => '2025-01-01',
                'timeprod' => NULL,
                'timeint' => NULL,
                'iohexol' => NULL,
                'dateinlab' => NULL,
                'timeinlab' => NULL,
                'staffcode' => NULL,
                'labstaff' => NULL,
                'checker' => NULL,
                'rcdr' => NULL,
                'version' => 1,
                'created_at' => '2025-09-02 15:10:46',
                'updated_at' => '2025-09-02 15:10:46',
            ),
            3 => 
            array (
                'labno' => '1111114',
                'specno' => '0000003',
                'spectype' => 4,
                'stid' => '2231405',
                'cno' => NULL,
                'accForm' => 'TestEntry',
                'repeat_sample' => 0,
                'pregnant' => NULL,
                'curmens' => 0,
                'mens2d' => 0,
                'basefoll' => NULL,
                'fast' => NULL,
                'venepunc' => NULL,
                'volume' => NULL,
                'tubes' => NULL,
                'stooltype' => NULL,
                'stoolusual' => NULL,
                'spectime' => NULL,
                'datecol' => '2025-01-01',
                'timeprod' => NULL,
                'timeint' => NULL,
                'iohexol' => NULL,
                'dateinlab' => NULL,
                'timeinlab' => NULL,
                'staffcode' => NULL,
                'labstaff' => NULL,
                'checker' => NULL,
                'rcdr' => NULL,
                'version' => 1,
                'created_at' => '2025-09-02 15:12:11',
                'updated_at' => '2025-09-02 15:12:11',
            ),
            4 => 
            array (
                'labno' => '1111115',
                'specno' => '0000004',
                'spectype' => 5,
                'stid' => '2231405',
                'cno' => NULL,
                'accForm' => 'TestEntry',
                'repeat_sample' => 0,
                'pregnant' => NULL,
                'curmens' => 0,
                'mens2d' => 0,
                'basefoll' => NULL,
                'fast' => NULL,
                'venepunc' => NULL,
                'volume' => NULL,
                'tubes' => NULL,
                'stooltype' => NULL,
                'stoolusual' => NULL,
                'spectime' => NULL,
                'datecol' => '2025-01-01',
                'timeprod' => NULL,
                'timeint' => NULL,
                'iohexol' => NULL,
                'dateinlab' => NULL,
                'timeinlab' => NULL,
                'staffcode' => NULL,
                'labstaff' => NULL,
                'checker' => NULL,
                'rcdr' => NULL,
                'version' => 1,
                'created_at' => '2025-09-02 15:12:28',
                'updated_at' => '2025-09-02 15:12:28',
            ),
        ));
        
        
    }
}